import assert from "node:assert/strict";
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";

const runnerSource = readFileSync(new URL("./run-supabase-rls.integration.mjs", import.meta.url), "utf8");
const verifiedRunnerSource = readFileSync(new URL("../scripts/run-supabase-rls.mjs", import.meta.url), "utf8");
const integrationSourceUrl = new URL("./supabase-rls.integration.mjs", import.meta.url);
const packageJson = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));

const anchor = "    // Field identity fixtures are complete.";

const plannerLines = [
  "    const plannerTeamA = fieldTeamA;",
  '    const otherPlannerTeamA = source("planner-team-other-a");',
  '    const assignedPlannerA = source("planner-assigned-a");',
  '    const foreignPlannerA = source("planner-foreign-a");',
  '    const selfCreatedPlannerA = source("planner-self-created-a");',
  '    const unassignedFieldPlannerA = source("planner-unassigned-field-a");',
  '    const forgedCoworkerPlannerA = source("planner-forged-coworker-a");',
  '    const forgedMissingPlannerA = source("planner-forged-missing-a");',
  '    const forgedCrossTenantPlannerA = source("planner-forged-cross-tenant-a");',
  '    const forgedDuplicatePlannerA = source("planner-forged-duplicate-a");',
  '    const forgedNonStringPlannerA = source("planner-forged-non-string-a");',
  '    const forgedPaddedPlannerA = source("planner-forged-padded-a");',
  '    const officeMultiPlannerA = source("planner-office-multi-a");',
  '    const deletablePlannerTeamA = source("planner-deletable-team-a");',
  '    const deletablePlannerA = source("planner-deletable-a");',
  '    const deletedMemberPlannerA = source("planner-deleted-member-a");',
  '    const historicalPlannerTeamA = source("planner-historical-team-a");',
  '    const historicalPlannerA = source("planner-historical-a");',
  '    const cancelledHistoricalPlannerA = source("planner-historical-cancelled-a");',
  '    const crossTenantPlannerTeamB = source("planner-team-b");',
  "",
  "    await expectAllowed(",
  '      await insertRecord(accounts.A.office, "team_members", typedRecord(organisationA, otherPlannerTeamA, null, null, { name: "Other planner worker", email: "other-planner@example.com", role: "Electrician", status: "Active" })),',
  '      "Office should create another planner team identity",',
  "    );",
  "    await expectAllowed(",
  '      await insertRecord(accounts.B.office, "team_members", typedRecord(organisationB, crossTenantPlannerTeamB, null, null, { name: "Tenant B planner worker", email: accounts.B.electrician.email, role: "Electrician", status: "Active" })),',
  '      "Tenant B office should create its planner team identity",',
  "    );",
  "    await expectAllowed(",
  '      await insertRecord(accounts.A.office, "team_members", typedRecord(organisationA, deletablePlannerTeamA, null, null, { name: "Reassign before deletion", email: "deletable-planner@example.com", role: "Electrician", status: "Active" })),',
  '      "Office should create a team member for assignment-deletion testing",',
  "    );",
  "    await expectAllowed(",
  '      await insertRecord(accounts.A.office, "team_members", typedRecord(organisationA, historicalPlannerTeamA, null, null, { name: "Historical planner worker", email: "historical-planner@example.com", role: "Electrician", status: "Active" })),',
  '      "Office should create a team member for planner history",',
  "    );",
  "    await expectAllowed(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, assignedPlannerA, customerA, jobA, { id: assignedPlannerA, title: "Assigned visit", type: "Job", date: "2026-08-10", startTime: "08:00", endTime: "16:00", customerId: customerA, jobId: jobA, teamMemberIds: [plannerTeamA], location: "1 Test Street", notes: "Assigned private site note", status: "Confirmed", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "Office should create an assigned planner entry",',
  "    );",
  "    await expectAllowed(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, foreignPlannerA, customerA, jobA, { id: foreignPlannerA, title: "Other worker visit", type: "Job", date: "2026-08-10", startTime: "09:00", endTime: "17:00", customerId: customerA, jobId: jobA, teamMemberIds: [otherPlannerTeamA], location: "2 Private Street", notes: "Other engineer note", status: "Confirmed", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "Office should create another worker planner entry",',
  "    );",
  "    await expectAllowed(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, officeMultiPlannerA, customerA, jobA, { id: officeMultiPlannerA, title: "Two worker visit", type: "Job", date: "2026-08-12", startTime: "08:00", endTime: "16:00", customerId: customerA, jobId: jobA, teamMemberIds: [plannerTeamA, otherPlannerTeamA], location: "1 Test Street", notes: "Office assigned team", status: "Confirmed", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "Office should create a valid multi-person planner assignment",',
  "    );",
  "    await expectAllowed(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, deletablePlannerA, customerA, jobA, { id: deletablePlannerA, title: "Reassignment required", type: "Job", date: "2026-08-13", startTime: "08:00", endTime: "10:00", customerId: customerA, jobId: jobA, teamMemberIds: [deletablePlannerTeamA], location: "1 Test Street", notes: "Active assignment", status: "Confirmed", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "Office should create an entry for team deletion protection",',
  "    );",
  "    await expectAllowed(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, historicalPlannerA, customerA, jobA, { id: historicalPlannerA, title: "Historical visit", type: "Job", date: "2026-08-01", startTime: "08:00", endTime: "10:00", customerId: customerA, jobId: jobA, teamMemberIds: [historicalPlannerTeamA], location: "1 Test Street", notes: "Completed history", status: "Complete", createdAt: "2026-08-01T00:00:00.000Z", updatedAt: "2026-08-01T10:00:00.000Z" })),',
  '      "Office should create a planner entry that will become history",',
  "    );",
  "    await expectAllowed(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, cancelledHistoricalPlannerA, customerA, jobA, { id: cancelledHistoricalPlannerA, title: "Cancelled historical visit", type: "Job", date: "2026-08-02", startTime: "08:00", endTime: "10:00", customerId: customerA, jobId: jobA, teamMemberIds: [historicalPlannerTeamA], location: "1 Test Street", notes: "Cancelled history", status: "Cancelled", createdAt: "2026-08-02T00:00:00.000Z", updatedAt: "2026-08-02T10:00:00.000Z" })),',
  '      "Office should create cancelled planner history",',
  "    );",
  "",
  '    const officePlannerRead = await listRecords(accounts.A.office, "planner_entries", "select=source_id");',
  '    await expectAllowed(officePlannerRead, "Office planner query should execute");',
  '    assert.ok(officePlannerRead.payload.some((row) => row.source_id === assignedPlannerA), "Office should read assigned entries");',
  '    assert.ok(officePlannerRead.payload.some((row) => row.source_id === foreignPlannerA), "Office should read other worker entries");',
  "",
  '    const electricianAssignedPlanner = await listRecords(accounts.A.electrician, "planner_entries", \\`select=source_id,payload&source_id=eq.\\${assignedPlannerA}\\`);',
  '    await expectAllowed(electricianAssignedPlanner, "Electrician assigned planner query should execute");',
  '    assert.equal(electricianAssignedPlanner.payload.length, 1, "Electrician should read an entry assigned to their team identity");',
  '    const electricianForeignPlanner = await listRecords(accounts.A.electrician, "planner_entries", \\`select=source_id&source_id=eq.\\${foreignPlannerA}\\`);',
  '    await expectAllowed(electricianForeignPlanner, "Electrician foreign planner query should fail closed");',
  '    assert.deepEqual(electricianForeignPlanner.payload, [], "Electrician must not read another worker planner entry");',
  "",
  "    await expectAllowed(",
  '      await insertRecord(accounts.A.electrician, "planner_entries", typedRecord(organisationA, selfCreatedPlannerA, customerA, jobA, { id: selfCreatedPlannerA, title: "Field follow-up", type: "Job", date: "2026-08-11", startTime: "08:00", endTime: "10:00", customerId: customerA, jobId: jobA, teamMemberIds: [plannerTeamA], location: "1 Test Street", notes: "Self assigned", status: "Planned", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "Electrician should create a planner entry that includes their team identity",',
  "    );",
  "    await expectDenied(",
  '      await insertRecord(accounts.A.electrician, "planner_entries", typedRecord(organisationA, unassignedFieldPlannerA, customerA, jobA, { id: unassignedFieldPlannerA, title: "Forged coworker visit", type: "Job", date: "2026-08-11", startTime: "10:00", endTime: "12:00", customerId: customerA, jobId: jobA, teamMemberIds: [otherPlannerTeamA], location: "2 Private Street", notes: "Not self assigned", status: "Planned", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "Electrician must not create a planner entry without their team identity",',
  "    );",
  "    await expectDenied(",
  '      await insertRecord(accounts.A.electrician, "planner_entries", typedRecord(organisationA, forgedCoworkerPlannerA, customerA, jobA, { id: forgedCoworkerPlannerA, title: "Forged shared visit", type: "Job", date: "2026-08-11", startTime: "12:00", endTime: "13:00", customerId: customerA, jobId: jobA, teamMemberIds: [plannerTeamA, otherPlannerTeamA], location: "1 Test Street", notes: "Added coworker", status: "Planned", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "Electrician must not add a coworker while retaining their own assignment",',
  "    );",
  "    await expectDeniedWithCode(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, forgedMissingPlannerA, customerA, jobA, { id: forgedMissingPlannerA, title: "Missing worker visit", type: "Job", date: "2026-08-11", startTime: "13:00", endTime: "14:00", customerId: customerA, jobId: jobA, teamMemberIds: [source("missing-planner-team")], location: "1 Test Street", notes: "Missing worker", status: "Planned", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "23503",',
  '      "Office must not add a nonexistent team assignment",',
  "    );",
  "    await expectDeniedWithCode(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, forgedCrossTenantPlannerA, customerA, jobA, { id: forgedCrossTenantPlannerA, title: "Cross-tenant worker visit", type: "Job", date: "2026-08-11", startTime: "14:00", endTime: "15:00", customerId: customerA, jobId: jobA, teamMemberIds: [crossTenantPlannerTeamB], location: "1 Test Street", notes: "Foreign worker", status: "Planned", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "23503",',
  '      "Office must not add a cross-tenant team assignment",',
  "    );",
  "    await expectDeniedWithCode(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, forgedDuplicatePlannerA, customerA, jobA, { id: forgedDuplicatePlannerA, title: "Duplicate worker visit", type: "Job", date: "2026-08-11", startTime: "14:30", endTime: "15:30", customerId: customerA, jobId: jobA, teamMemberIds: [otherPlannerTeamA, otherPlannerTeamA], location: "1 Test Street", notes: "Duplicate worker", status: "Planned", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "23503",',
  '      "Office must not create duplicate team assignments",',
  "    );",
  "    await expectDeniedWithCode(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, forgedNonStringPlannerA, customerA, jobA, { id: forgedNonStringPlannerA, title: "Invalid worker visit", type: "Job", date: "2026-08-11", startTime: "14:45", endTime: "15:45", customerId: customerA, jobId: jobA, teamMemberIds: [otherPlannerTeamA, 42], location: "1 Test Street", notes: "Invalid worker", status: "Planned", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "23503",',
  '      "Office must not create non-string team assignments",',
  "    );",
  "    await expectDeniedWithCode(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, forgedPaddedPlannerA, customerA, jobA, { id: forgedPaddedPlannerA, title: "Padded worker identity", type: "Job", date: "2026-08-11", startTime: "15:00", endTime: "16:00", customerId: customerA, jobId: jobA, teamMemberIds: [" " + otherPlannerTeamA + " "], location: "1 Test Street", notes: "Noncanonical identity", status: "Planned", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T00:00:00.000Z" })),',
  '      "23503",',
  '      "Office must not create a whitespace-padded team assignment",',
  "    );",
  "",
  '    const electricianPlannerUpdate = await patchRecords(accounts.A.electrician, "planner_entries", \\`source_id=eq.\\${assignedPlannerA}\\`, { payload: { id: assignedPlannerA, title: "Assigned visit updated", type: "Job", date: "2026-08-10", startTime: "08:00", endTime: "16:30", customerId: customerA, jobId: jobA, teamMemberIds: [plannerTeamA], location: "1 Test Street", notes: "Field update", status: "Complete", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T12:00:00.000Z" } });',
  '    await expectAllowed(electricianPlannerUpdate, "Electrician should update a planner entry while retaining their assignment");',
  '    assert.equal(electricianPlannerUpdate.payload.length, 1, "Electrician operational update must affect one planner row");',
  '    assert.equal(electricianPlannerUpdate.payload[0]?.payload?.title, "Assigned visit updated");',
  '    assert.equal(electricianPlannerUpdate.payload[0]?.payload?.status, "Complete");',
  '    const electricianMultiPlannerUpdate = await patchRecords(accounts.A.electrician, "planner_entries", "source_id=eq." + officeMultiPlannerA, { payload: { id: officeMultiPlannerA, title: "Two worker visit updated", type: "Job", date: "2026-08-12", startTime: "08:00", endTime: "16:30", customerId: customerA, jobId: jobA, teamMemberIds: [plannerTeamA, otherPlannerTeamA], location: "1 Test Street", notes: "Operational update only", status: "Complete", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T12:00:00.000Z" } });',
  '    await expectAllowed(electricianMultiPlannerUpdate, "Electrician should update operational fields while preserving an office multi-person assignment");',
  '    assert.equal(electricianMultiPlannerUpdate.payload.length, 1, "Electrician multi-person operational update must affect one planner row");',
  '    assert.deepEqual(electricianMultiPlannerUpdate.payload[0]?.payload?.teamMemberIds, [plannerTeamA, otherPlannerTeamA]);',
  '    assert.equal(electricianMultiPlannerUpdate.payload[0]?.payload?.title, "Two worker visit updated");',
  "    await expectDenied(",
  '      await patchRecords(accounts.A.electrician, "planner_entries", "source_id=eq." + assignedPlannerA, { payload: { id: assignedPlannerA, title: "Assigned visit updated", type: "Job", date: "2026-08-10", startTime: "08:00", endTime: "16:30", customerId: customerA, jobId: jobA, teamMemberIds: [plannerTeamA, otherPlannerTeamA], location: "1 Test Street", notes: "Forged coworker", status: "Complete", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T12:00:00.000Z" } }),',
  '      "Electrician must not add a coworker to an existing planner assignment",',
  "    );",
  "    await expectDenied(",
  '      await patchRecords(accounts.A.electrician, "planner_entries", \\`source_id=eq.\\${assignedPlannerA}\\`, { payload: { id: assignedPlannerA, title: "Reassigned visit", type: "Job", date: "2026-08-10", startTime: "08:00", endTime: "16:30", customerId: customerA, jobId: jobA, teamMemberIds: [otherPlannerTeamA], location: "1 Test Street", notes: "Removed self", status: "Complete", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T12:00:00.000Z" } }),',
  '      "Electrician must not remove their assignment from a planner entry",',
  "    );",
  '    const officePlannerReassignment = await patchRecords(accounts.A.office, "planner_entries", "source_id=eq." + officeMultiPlannerA, { payload: { id: officeMultiPlannerA, title: "Single worker visit", type: "Job", date: "2026-08-12", startTime: "08:00", endTime: "16:30", customerId: customerA, jobId: jobA, teamMemberIds: [plannerTeamA], location: "1 Test Street", notes: "Office reassigned", status: "Confirmed", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T13:00:00.000Z" } });',
  '    await expectAllowed(officePlannerReassignment, "Office should update a planner team assignment to another valid set");',
  '    assert.equal(officePlannerReassignment.payload.length, 1, "Office assignment rewrite must affect one planner row");',
  '    assert.deepEqual(officePlannerReassignment.payload[0]?.payload?.teamMemberIds, [plannerTeamA]);',
  '    const canonicalPlannerAfterDeniedUpdate = await listRecords(accounts.A.office, "planner_entries", "select=payload&source_id=eq." + assignedPlannerA);',
  '    await expectAllowed(canonicalPlannerAfterDeniedUpdate, "Office should inspect the canonical planner assignment after denied field writes");',
  '    assert.deepEqual(canonicalPlannerAfterDeniedUpdate.payload[0]?.payload?.teamMemberIds, [plannerTeamA], "Denied electrician writes must leave the canonical assignment unchanged");',
  "",
  "    await expectDeniedWithCode(",
  '      await patchRecords(accounts.A.owner, "team_members", "source_id=eq." + deletablePlannerTeamA, { deleted_at: new Date().toISOString() }),',
  '      "23503",',
  '      "An actively assigned team member must not be deleted",',
  "    );",
  "    await expectDeniedWithCode(",
  '      await deleteRecords(accounts.A.owner, "team_members", "source_id=eq." + deletablePlannerTeamA),',
  '      "23503",',
  '      "An actively assigned team member must not be permanently deleted",',
  "    );",
  '    const activePlannerReassignment = await patchRecords(accounts.A.office, "planner_entries", "source_id=eq." + deletablePlannerA, { payload: { id: deletablePlannerA, title: "Reassigned visit", type: "Job", date: "2026-08-13", startTime: "08:00", endTime: "10:00", customerId: customerA, jobId: jobA, teamMemberIds: [otherPlannerTeamA], location: "1 Test Street", notes: "Safely reassigned", status: "Confirmed", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T14:00:00.000Z" } });',
  '    await expectAllowed(activePlannerReassignment, "Office should reassign an active planner entry before deleting a team member");',
  '    assert.equal(activePlannerReassignment.payload.length, 1, "Active planner reassignment must affect one row");',
  '    assert.deepEqual(activePlannerReassignment.payload[0]?.payload?.teamMemberIds, [otherPlannerTeamA]);',
  '    const softDeletedReassignedMember = await patchRecords(accounts.A.owner, "team_members", "source_id=eq." + deletablePlannerTeamA, { deleted_at: new Date().toISOString() });',
  '    await expectAllowed(softDeletedReassignedMember, "Owner should delete a team member after active planner reassignment");',
  '    assert.equal(softDeletedReassignedMember.payload.length, 1, "Team-member tombstone must affect one row");',
  '    assert.ok(softDeletedReassignedMember.payload[0]?.deleted_at, "Team-member tombstone must be returned");',
  "    await expectDeniedWithCode(",
  '      await insertRecord(accounts.A.office, "planner_entries", typedRecord(organisationA, deletedMemberPlannerA, customerA, jobA, { id: deletedMemberPlannerA, title: "Deleted worker visit", type: "Job", date: "2026-08-14", startTime: "08:00", endTime: "10:00", customerId: customerA, jobId: jobA, teamMemberIds: [deletablePlannerTeamA], location: "1 Test Street", notes: "Deleted assignment", status: "Planned", createdAt: "2026-08-09T00:00:00.000Z", updatedAt: "2026-08-09T15:00:00.000Z" })),',
  '      "23503",',
  '      "Office must not assign a deleted team member to an active planner entry",',
  "    );",
  '    const hardDeletedReassignedMember = await deleteRecords(accounts.A.owner, "team_members", "source_id=eq." + deletablePlannerTeamA);',
  '    await expectAllowed(hardDeletedReassignedMember, "Owner should permanently delete a team member after active planner reassignment");',
  '    assert.equal(hardDeletedReassignedMember.payload.length, 1, "Reassigned team-member hard delete must affect one row");',
  '    assert.equal(hardDeletedReassignedMember.payload[0]?.source_id, deletablePlannerTeamA);',
  '    const softDeletedHistoricalMember = await patchRecords(accounts.A.owner, "team_members", "source_id=eq." + historicalPlannerTeamA, { deleted_at: new Date().toISOString() });',
  '    await expectAllowed(softDeletedHistoricalMember, "Owner should delete a team member referenced only by completed and cancelled planner history");',
  '    assert.equal(softDeletedHistoricalMember.payload.length, 1, "Historical team-member tombstone must affect one row");',
  '    assert.ok(softDeletedHistoricalMember.payload[0]?.deleted_at, "Historical team-member tombstone must be returned");',
  "    await expectDeniedWithCode(",
  '      await patchRecords(accounts.A.office, "planner_entries", "source_id=eq." + historicalPlannerA, { payload: { id: historicalPlannerA, title: "Reopened completed visit", type: "Job", date: "2026-08-01", startTime: "08:00", endTime: "10:00", customerId: customerA, jobId: jobA, teamMemberIds: [historicalPlannerTeamA], location: "1 Test Street", notes: "Must stay historical", status: "Confirmed", createdAt: "2026-08-01T00:00:00.000Z", updatedAt: "2026-08-10T00:00:00.000Z" } }),',
  '      "23503",',
  '      "Completed planner history must not reopen with a deleted assignee",',
  "    );",
  "    await expectDeniedWithCode(",
  '      await patchRecords(accounts.A.office, "planner_entries", "source_id=eq." + cancelledHistoricalPlannerA, { payload: { id: cancelledHistoricalPlannerA, title: "Reopened cancelled visit", type: "Job", date: "2026-08-02", startTime: "08:00", endTime: "10:00", customerId: customerA, jobId: jobA, teamMemberIds: [historicalPlannerTeamA], location: "1 Test Street", notes: "Must stay cancelled", status: "Planned", createdAt: "2026-08-02T00:00:00.000Z", updatedAt: "2026-08-10T00:00:00.000Z" } }),',
  '      "23503",',
  '      "Cancelled planner history must not reopen with a deleted assignee",',
  "    );",
  '    const completedHistoryAfterTeamDelete = await listRecords(accounts.A.office, "planner_entries", "select=source_id,payload,deleted_at&source_id=eq." + historicalPlannerA);',
  '    await expectAllowed(completedHistoryAfterTeamDelete, "Office should retain completed planner history after team deletion");',
  '    assert.equal(completedHistoryAfterTeamDelete.payload.length, 1);',
  '    assert.equal(completedHistoryAfterTeamDelete.payload[0]?.payload?.status, "Complete");',
  '    assert.equal(completedHistoryAfterTeamDelete.payload[0]?.deleted_at, null);',
  '    const cancelledHistoryAfterTeamDelete = await listRecords(accounts.A.office, "planner_entries", "select=source_id,payload,deleted_at&source_id=eq." + cancelledHistoricalPlannerA);',
  '    await expectAllowed(cancelledHistoryAfterTeamDelete, "Office should retain cancelled planner history after team deletion");',
  '    assert.equal(cancelledHistoryAfterTeamDelete.payload.length, 1);',
  '    assert.equal(cancelledHistoryAfterTeamDelete.payload[0]?.payload?.status, "Cancelled");',
  '    assert.equal(cancelledHistoryAfterTeamDelete.payload[0]?.deleted_at, null);',
  "    await expectDeniedWithCode(",
  '      await deleteRecords(accounts.A.owner, "team_members", "source_id=eq." + historicalPlannerTeamA),',
  '      "23503",',
  '      "Retained planner history must block permanent team-member deletion",',
  "    );",
  '    const completedHistoryTombstone = await patchRecords(accounts.A.owner, "planner_entries", "source_id=eq." + historicalPlannerA, { deleted_at: new Date().toISOString() });',
  '    await expectAllowed(completedHistoryTombstone, "Owner should tombstone completed planner history before permanent member deletion");',
  '    assert.equal(completedHistoryTombstone.payload.length, 1, "Completed history tombstone must affect one row");',
  '    assert.ok(completedHistoryTombstone.payload[0]?.deleted_at, "Completed history tombstone must be returned");',
  '    const cancelledHistoryTombstone = await patchRecords(accounts.A.owner, "planner_entries", "source_id=eq." + cancelledHistoricalPlannerA, { deleted_at: new Date().toISOString() });',
  '    await expectAllowed(cancelledHistoryTombstone, "Owner should tombstone cancelled planner history before permanent member deletion");',
  '    assert.equal(cancelledHistoryTombstone.payload.length, 1, "Cancelled history tombstone must affect one row");',
  '    assert.ok(cancelledHistoryTombstone.payload[0]?.deleted_at, "Cancelled history tombstone must be returned");',
  '    const hardDeletedHistoricalMember = await deleteRecords(accounts.A.owner, "team_members", "source_id=eq." + historicalPlannerTeamA);',
  '    await expectAllowed(hardDeletedHistoricalMember, "Owner should permanently delete a historical member after tombstoning retained planner history");',
  '    assert.equal(hardDeletedHistoricalMember.payload.length, 1, "Historical team-member hard delete must affect one row");',
  '    assert.equal(hardDeletedHistoricalMember.payload[0]?.source_id, historicalPlannerTeamA);',
  "",
  '    const customerPlannerRead = await listRecords(accounts.A.customer, "planner_entries", \\`select=source_id&source_id=eq.\\${assignedPlannerA}\\`);',
  '    await expectAllowed(customerPlannerRead, "Customer planner query should fail closed");',
  '    assert.deepEqual(customerPlannerRead.payload, [], "Customers must not read internal planner entries");',
  '    const crossTenantPlannerRead = await listRecords(accounts.B.electrician, "planner_entries", \\`select=source_id&source_id=eq.\\${assignedPlannerA}\\`);',
  '    await expectAllowed(crossTenantPlannerRead, "Cross-tenant planner query should execute safely");',
  '    assert.deepEqual(crossTenantPlannerRead.payload, [], "Another organisation must not read the planner entry");',
];

const plannerCoverage = `${anchor}\\n\\n${plannerLines.join("\\n")}`;

test("live RLS runner proves planner entries are assignment scoped", () => {
  assert.equal(
    packageJson.scripts["test:rls"],
    "node scripts/run-supabase-rls.mjs",
    "The disposable Supabase workflow must execute the verified RLS runner",
  );
  assert.match(
    verifiedRunnerSource,
    /spawn\(nodeExecutable, \["--test", "tests\/planner-team-live-rls\.test\.mjs"\]/,
    "The verified RLS runner must execute the planner penetration wrapper",
  );
  const occurrences = runnerSource.split(anchor).length - 1;
  assert.equal(occurrences, 1, `Expected one completed field identity anchor, found ${occurrences}`);

  const patchedRunner = runnerSource.replace(anchor, plannerCoverage);
  for (const phrase of [
    "Electrician should read an entry assigned to their team identity",
    "Electrician must not read another worker planner entry",
    "Electrician should create a planner entry that includes their team identity",
    "Electrician must not create a planner entry without their team identity",
    "Electrician must not add a coworker while retaining their own assignment",
    "Office must not add a nonexistent team assignment",
    "Office must not add a cross-tenant team assignment",
    "Office must not create duplicate team assignments",
    "Office must not create non-string team assignments",
    "Office must not create a whitespace-padded team assignment",
    "Electrician should update a planner entry while retaining their assignment",
    "Electrician should update operational fields while preserving an office multi-person assignment",
    "Electrician must not add a coworker to an existing planner assignment",
    "Electrician must not remove their assignment from a planner entry",
    "Office should create a valid multi-person planner assignment",
    "Office should update a planner team assignment to another valid set",
    "An actively assigned team member must not be deleted",
    "An actively assigned team member must not be permanently deleted",
    "Office should reassign an active planner entry before deleting a team member",
    "Owner should delete a team member after active planner reassignment",
    "Owner should permanently delete a team member after active planner reassignment",
    "Office must not assign a deleted team member to an active planner entry",
    "Owner should delete a team member referenced only by completed and cancelled planner history",
    "Completed planner history must not reopen with a deleted assignee",
    "Cancelled planner history must not reopen with a deleted assignee",
    "Retained planner history must block permanent team-member deletion",
    "Owner should tombstone completed planner history before permanent member deletion",
    "Owner should tombstone cancelled planner history before permanent member deletion",
    "Owner should permanently delete a historical member after tombstoning retained planner history",
    "Denied electrician writes must leave the canonical assignment unchanged",
    "Customers must not read internal planner entries",
    "Another organisation must not read the planner entry",
  ]) {
    assert.match(patchedRunner, new RegExp(phrase.replaceAll(" ", "\\s+"), "i"));
  }

  const temporaryDirectory = mkdtempSync(join(tmpdir(), "jr-os-planner-rls-"));
  const temporaryRunner = join(temporaryDirectory, "run-supabase-rls.integration.mjs");
  const temporaryIntegration = join(temporaryDirectory, "supabase-rls.integration.mjs");
  try {
    writeFileSync(temporaryRunner, patchedRunner, "utf8");
    copyFileSync(integrationSourceUrl, temporaryIntegration);
    const childEnvironment = { ...process.env };
    delete childEnvironment.NODE_TEST_CONTEXT;
    const result = spawnSync(process.execPath, [temporaryRunner], {
      cwd: process.cwd(),
      env: childEnvironment,
      stdio: "inherit",
    });
    if (result.error) throw result.error;
    assert.equal(result.status ?? 1, 0, "Planner live RLS wrapper should complete successfully");
  } finally {
    rmSync(temporaryDirectory, { recursive: true, force: true });
  }
});
