import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";

const runnerSource = readFileSync(new URL("./run-supabase-rls.integration.mjs", import.meta.url), "utf8");
const integrationSource = readFileSync(new URL("./supabase-rls.integration.mjs", import.meta.url), "utf8");

function lines(...values) {
  return values.join("\n");
}

const ownMetadata = lines(
  '    await expectAllowed(await insertRecord(accounts.A.electrician, "private_files", {',
  '      organisation_id: organisationA, source_id: source("file-own"), job_source_id: jobA, customer_source_id: customerA,',
  '      bucket, object_path: ownPath, file_name: "photo.png", mime_type: "image/png",',
  '    }), "Staff should write private file metadata");',
);

const safeOwnMetadata = lines(
  '    await expectDenied(await insertRecord(accounts.A.electrician, "private_files", {',
  '      organisation_id: organisationA, source_id: source("file-field-denied"), storage_key: "jr-os-job-documents", job_source_id: jobA, customer_source_id: customerA,',
  '      bucket, object_path: ownPath, file_name: "photo.png", mime_type: "image/png",',
  '    }), "Electrician must not register field file metadata without an assigned upload intent");',
  '    await expectAllowed(',
  '      await insertRecord(accounts.A.office, "job_documents", typedRecord(organisationA, source("file-own"), null, jobA, { name: "Assigned photo", category: "Photo" })),',
  '      "Office should create the production-shaped job document backing the private file",',
  '    );',
  '    await expectAllowed(await insertRecord(accounts.A.office, "private_files", {',
  '      organisation_id: organisationA, source_id: source("file-own"), storage_key: "jr-os-job-documents", job_source_id: jobA, customer_source_id: customerA,',
  '      bucket, object_path: ownPath, file_name: "photo.png", mime_type: "image/png",',
  '    }), "Office should register field file metadata");',
);

const otherCustomerMetadata = lines(
  '    await expectAllowed(await insertRecord(accounts.A.office, "private_files", {',
  '      organisation_id: organisationA, source_id: source("file-other"), job_source_id: otherCustomerJobA, customer_source_id: otherCustomerA,',
  '      bucket, object_path: otherCustomerPath, file_name: "other.png", mime_type: "image/png",',
  '    }), "Office should write other-customer file metadata");',
);

const safeOtherCustomerMetadata = lines(
  '    await expectAllowed(',
  '      await insertRecord(accounts.A.office, "job_documents", typedRecord(organisationA, source("file-other"), null, otherCustomerJobA, { name: "Unassigned photo", category: "Photo" })),',
  '      "Office should create the unassigned job document backing the private file",',
  '    );',
  '    await expectAllowed(await insertRecord(accounts.A.office, "private_files", {',
  '      organisation_id: organisationA, source_id: source("file-other"), storage_key: "jr-os-job-documents", job_source_id: otherCustomerJobA, customer_source_id: otherCustomerA,',
  '      bucket, object_path: otherCustomerPath, file_name: "other.png", mime_type: "image/png",',
  '    }), "Office should write other-customer file metadata");',
);

const roleCoverage = lines(
  '',
  '    await expectAllowed(await patchRecords(accounts.A.office, "team_members", "source_id=eq." + fieldTeamCoworkerA, { payload: { id: fieldTeamCoworkerA, name: "Field coworker", email: accounts.A.coworker.email, role: "Electrician", status: "Active" } }), "Office should reactivate the unique coworker identity for co-assigned file reads");',
  '    await expectAllowed(',
  '      await downloadStorageObject(accounts.A.electrician, ownPath),',
  '      "Electrician should download a field job document",',
  '    );',
  '    const assignedJobDocumentMetadata = await listRecords(accounts.A.electrician, "private_files", "select=source_id&source_id=eq." + source("file-own"));',
  '    await expectAllowed(assignedJobDocumentMetadata, "Assigned job-document metadata query should execute");',
  '    assert.equal(assignedJobDocumentMetadata.payload.length, 1, "Electrician should read assigned job-document metadata");',
  '    const coworkerJobDocumentMetadata = await listRecords(accounts.A.coworker, "private_files", "select=source_id&source_id=eq." + source("file-own"));',
  '    await expectAllowed(coworkerJobDocumentMetadata, "Co-assigned job-document metadata query should execute");',
  '    assert.equal(coworkerJobDocumentMetadata.payload.length, 1, "Co-assigned electrician should read assigned job-document metadata");',
  '    await expectAllowed(await patchRecords(accounts.A.owner, "job_documents", "source_id=eq." + source("file-own"), { deleted_at: new Date().toISOString() }), "Owner should soft-delete the private file backing document");',
  '    const deletedJobDocumentMetadata = await listRecords(accounts.A.electrician, "private_files", "select=source_id&source_id=eq." + source("file-own"));',
  '    await expectAllowed(deletedJobDocumentMetadata, "Deleted job-document metadata query should execute safely");',
  '    assert.deepEqual(deletedJobDocumentMetadata.payload, [], "Electrician must not read metadata for a soft-deleted job document");',
  '    await expectDenied(',
  '      await downloadStorageObject(accounts.A.electrician, ownPath),',
  '      "Electrician must not download a soft-deleted job document",',
  '    );',
  '    const officeDeletedJobDocumentMetadata = await listRecords(accounts.A.office, "private_files", "select=source_id&source_id=eq." + source("file-own"));',
  '    await expectAllowed(officeDeletedJobDocumentMetadata, "Office deleted job-document metadata query should execute");',
  '    assert.equal(officeDeletedJobDocumentMetadata.payload.length, 1, "Office should retain metadata for a soft-deleted job document");',
  '    await expectAllowed(',
  '      await downloadStorageObject(accounts.A.office, ownPath),',
  '      "Office should retain soft-deleted job-document download access",',
  '    );',
  '    await expectAllowed(await patchRecords(accounts.A.owner, "job_documents", "source_id=eq." + source("file-own"), { deleted_at: null }), "Owner should restore the private file backing document after deletion coverage");',
  '    const restoredJobDocumentMetadata = await listRecords(accounts.A.electrician, "private_files", "select=source_id&source_id=eq." + source("file-own"));',
  '    await expectAllowed(restoredJobDocumentMetadata, "Restored job-document metadata query should execute");',
  '    assert.equal(restoredJobDocumentMetadata.payload.length, 1, "Electrician should regain assigned metadata only after document restoration");',
  '    await expectAllowed(',
  '      await downloadStorageObject(accounts.A.electrician, ownPath),',
  '      "Electrician should regain the assigned download only after document restoration",',
  '    );',
  '    const unassignedJobDocumentMetadata = await listRecords(accounts.A.electrician, "private_files", "select=source_id&source_id=eq." + source("file-other"));',
  '    await expectAllowed(unassignedJobDocumentMetadata, "Unassigned job-document metadata query should execute safely");',
  '    assert.deepEqual(unassignedJobDocumentMetadata.payload, [], "Electrician must not read unassigned job-document metadata");',
  '    await expectDenied(',
  '      await downloadStorageObject(accounts.A.electrician, otherCustomerPath),',
  '      "Electrician must not download an unassigned job document",',
  '    );',
  '    await expectAllowed(',
  '      await downloadStorageObject(accounts.A.office, otherCustomerPath),',
  '      "Office should retain unassigned job-document download access",',
  '    );',
  '    const crossTenantReadFile = source("file-cross-read");',
  '    const crossTenantReadPath = organisationB + "/jobs/" + jobB + "/" + crossTenantReadFile + "/cross-read.png";',
  '    context.objectPaths.push(crossTenantReadPath);',
  '    await expectAllowed(',
  '      await insertRecord(accounts.B.office, "job_documents", typedRecord(organisationB, crossTenantReadFile, null, jobB, { name: "Tenant B photo", category: "Photo" })),',
  '      "Tenant B office should create the cross-tenant private-file document",',
  '    );',
  '    await expectAllowed(',
  '      await uploadStorageObject(accounts.B.office, crossTenantReadPath, pngBytes, "image/png"),',
  '      "Tenant B office should upload the cross-tenant private-file object",',
  '    );',
  '    await expectAllowed(await insertRecord(accounts.B.office, "private_files", {',
  '      organisation_id: organisationB, source_id: crossTenantReadFile, storage_key: "jr-os-job-documents", job_source_id: jobB, customer_source_id: customerB,',
  '      bucket, object_path: crossTenantReadPath, file_name: "cross-read.png", mime_type: "image/png",',
  '    }), "Tenant B office should register the cross-tenant private-file metadata");',
  '    await expectDenied(',
  '      await downloadStorageObject(accounts.A.electrician, crossTenantReadPath),',
  '      "Assigned electrician must not download another organisation\'s job document",',
  '    );',
  '    await expectDenied(',
  '      await downloadStorageObject(accounts.A.customer, ownPath),',
  '      "Customer must not download an unshared job document",',
  '    );',
  '',
  '    const surveyPhotoFile = source("survey-photo-role");',
  '    const surveyPhotoPath = organisationA + "/jobs/" + jobA + "/" + surveyPhotoFile + "/survey.jpg";',
  '    context.objectPaths.push(surveyPhotoPath);',
  '    await expectDenied(',
  '      await uploadStorageObject(accounts.A.electrician, surveyPhotoPath, pngBytes, "image/jpeg"),',
  '      "Electrician must not upload a field survey photo without an assigned upload intent",',
  '    );',
  '    await expectDenied(await insertRecord(accounts.A.electrician, "private_files", {',
  '      organisation_id: organisationA, source_id: source("survey-photo-field-denied"), storage_key: "jr-os-surveys", job_source_id: jobA, customer_source_id: customerA,',
  '      bucket, object_path: surveyPhotoPath, file_name: "survey.jpg", mime_type: "image/jpeg",',
  '    }), "Electrician must not register field survey photo metadata without an assigned upload intent");',
  '    await expectAllowed(',
  '      await uploadStorageObject(accounts.A.office, surveyPhotoPath, pngBytes, "image/jpeg"),',
  '      "Office should upload the survey fixture",',
  '    );',
  '    await expectAllowed(await insertRecord(accounts.A.office, "private_files", {',
  '      organisation_id: organisationA, source_id: surveyPhotoFile, storage_key: "jr-os-surveys", job_source_id: jobA, customer_source_id: customerA,',
  '      bucket, object_path: surveyPhotoPath, file_name: "survey.jpg", mime_type: "image/jpeg",',
  '    }), "Office should register field survey photo metadata");',
  '    await expectAllowed(',
  '      await downloadStorageObject(accounts.A.electrician, surveyPhotoPath),',
  '      "Electrician should download a field survey photo",',
  '    );',
  '    const assignedSurveyPhotoMetadata = await listRecords(accounts.A.electrician, "private_files", "select=source_id&source_id=eq." + surveyPhotoFile);',
  '    await expectAllowed(assignedSurveyPhotoMetadata, "Assigned survey photo metadata query should execute");',
  '    assert.equal(assignedSurveyPhotoMetadata.payload.length, 1, "Electrician should read assigned survey photo metadata");',
  '    await expectDenied(',
  '      await downloadStorageObject(accounts.A.customer, surveyPhotoPath),',
  '      "Customer must not download an internal survey photo",',
  '    );',
  '',
  '    const unassignedSurveyPhotoSurvey = source("unassigned-survey-photo-survey");',
  '    const unassignedSurveyPhotoFile = source("unassigned-survey-photo-file");',
  '    const unassignedSurveyPhotoPath = organisationA + "/jobs/" + otherCustomerJobA + "/" + unassignedSurveyPhotoFile + "/survey.jpg";',
  '    context.objectPaths.push(unassignedSurveyPhotoPath);',
  '    await expectAllowed(await insertRecord(accounts.A.office, "cloud_collections", genericRecord(organisationA, "jr-os-surveys", unassignedSurveyPhotoSurvey, accounts.A.office, otherCustomerA, otherCustomerJobA, { number: "SUR-UNASSIGNED-PHOTO", status: "Draft", photos: [{ id: unassignedSurveyPhotoFile, name: "survey.jpg" }] })), "Office should create an unassigned survey photo fixture");',
  '    await expectAllowed(',
  '      await uploadStorageObject(accounts.A.office, unassignedSurveyPhotoPath, pngBytes, "image/jpeg"),',
  '      "Office should upload an unassigned survey photo fixture",',
  '    );',
  '    await expectAllowed(await insertRecord(accounts.A.office, "private_files", {',
  '      organisation_id: organisationA, source_id: unassignedSurveyPhotoFile, storage_key: "jr-os-surveys", job_source_id: otherCustomerJobA, customer_source_id: otherCustomerA,',
  '      bucket, object_path: unassignedSurveyPhotoPath, file_name: "survey.jpg", mime_type: "image/jpeg",',
  '    }), "Office should register unassigned survey photo metadata");',
  '    const unassignedSurveyPhotoMetadata = await listRecords(accounts.A.electrician, "private_files", "select=source_id&source_id=eq." + unassignedSurveyPhotoFile);',
  '    await expectAllowed(unassignedSurveyPhotoMetadata, "Unassigned survey photo metadata query should execute safely");',
  '    assert.deepEqual(unassignedSurveyPhotoMetadata.payload, [], "Electrician must not read unassigned survey photo metadata");',
  '    await expectDenied(',
  '      await downloadStorageObject(accounts.A.electrician, unassignedSurveyPhotoPath),',
  '      "Electrician must not download an unassigned survey photo",',
  '    );',
  '    await expectAllowed(',
  '      await downloadStorageObject(accounts.A.office, unassignedSurveyPhotoPath),',
  '      "Office should retain unassigned survey photo access",',
  '    );',
  '',
  '    const expenseReceiptFile = source("expense-receipt-role");',
  '    const expenseReceiptPath = organisationA + "/jobs/" + jobA + "/" + expenseReceiptFile + "/receipt.pdf";',
  '    context.objectPaths.push(expenseReceiptPath);',
  '    await expectAllowed(',
  '      await uploadStorageObject(accounts.A.office, expenseReceiptPath, new Uint8Array([37, 80, 68, 70]), "application/pdf"),',
  '      "Office should upload a private expense receipt",',
  '    );',
  '    await expectAllowed(await insertRecord(accounts.A.office, "private_files", {',
  '      organisation_id: organisationA, source_id: expenseReceiptFile, storage_key: "jr-os-expenses", job_source_id: jobA, customer_source_id: customerA,',
  '      bucket, object_path: expenseReceiptPath, file_name: "receipt.pdf", mime_type: "application/pdf",',
  '    }), "Office should register private expense receipt metadata");',
  '    const electricianExpenseMetadata = await listRecords(accounts.A.electrician, "private_files", "select=source_id&source_id=eq." + expenseReceiptFile);',
  '    await expectAllowed(electricianExpenseMetadata, "Electrician expense metadata query should fail closed");',
  '    assert.deepEqual(electricianExpenseMetadata.payload, [], "Electrician must not read expense receipt metadata");',
  '    const customerExpenseMetadata = await listRecords(accounts.A.customer, "private_files", "select=source_id&source_id=eq." + expenseReceiptFile);',
  '    await expectAllowed(customerExpenseMetadata, "Customer expense metadata query should fail closed");',
  '    assert.deepEqual(customerExpenseMetadata.payload, [], "Customer must not read expense receipt metadata");',
  '    await expectAllowed(',
  '      await downloadStorageObject(accounts.A.office, expenseReceiptPath),',
  '      "Office should download a private expense receipt",',
  '    );',
  '    await expectDenied(',
  '      await downloadStorageObject(accounts.A.electrician, expenseReceiptPath),',
  '      "Electrician must not download a private expense receipt",',
  '    );',
  '    await expectDenied(',
  '      await downloadStorageObject(accounts.A.customer, expenseReceiptPath),',
  '      "Customer must not download a private expense receipt",',
  '    );',
  '    await expectDenied(',
  '      await authenticated(accounts.A.electrician, "/storage/v1/object/" + bucket + "/" + encodedPath(expenseReceiptPath), {',
  '        method: "POST",',
  '        rawBody: new Uint8Array([37, 80, 68, 70, 45, 70, 79, 82, 71, 69, 68]),',
  '        extraHeaders: { "Content-Type": "application/pdf", "x-upsert": "true" },',
  '      }),',
  '      "Electrician must not overwrite a private expense receipt",',
  '    );',
  '',
  '    const unknownPrivateFile = source("unknown-private-role");',
  '    const unknownPrivatePath = organisationA + "/unassigned/" + unknownPrivateFile + "/unknown.txt";',
  '    context.objectPaths.push(unknownPrivatePath);',
  '    await expectAllowed(',
  '      await uploadStorageObject(accounts.A.office, unknownPrivatePath, new Uint8Array([117, 110, 107, 110, 111, 119, 110]), "text/plain"),',
  '      "Office should upload unknown historical-style private data",',
  '    );',
  '    await expectAllowed(await insertRecord(accounts.A.office, "private_files", {',
  '      organisation_id: organisationA, source_id: unknownPrivateFile, job_source_id: null, customer_source_id: null,',
  '      bucket, object_path: unknownPrivatePath, file_name: "unknown.txt", mime_type: "text/plain",',
  '    }), "Office should register unknown private metadata");',
  '    await expectAllowed(',
  '      await downloadStorageObject(accounts.A.office, unknownPrivatePath),',
  '      "Office should retain unknown private metadata access",',
  '    );',
  '    await expectDenied(',
  '      await downloadStorageObject(accounts.A.electrician, unknownPrivatePath),',
  '      "Electrician must not read unknown private metadata",',
  '    );',
  '    await expectDenied(',
  '      await downloadStorageObject(accounts.A.customer, unknownPrivatePath),',
  '      "Customer must not read unknown private metadata",',
  '    );',
);

const legacyUpload = lines(
  '    await expectAllowed(',
  '      await uploadStorageObject(accounts.A.electrician, legacyPath, pngBytes, "image/png", legacyBucket),',
  '      "Electrician should retain authenticated legacy upload compatibility",',
  '    );',
);

const safeLegacyUpload = lines(
  '    await expectDenied(',
  '      await uploadStorageObject(accounts.A.electrician, legacyPath, pngBytes, "image/png", legacyBucket),',
  '      "Electrician must not upload to metadata-less legacy storage",',
  '    );',
  '    await expectAllowed(',
  '      await uploadStorageObject(accounts.A.office, legacyPath, pngBytes, "image/png", legacyBucket),',
  '      "Office should retain authenticated legacy upload compatibility",',
  '    );',
  '    await expectAllowed(',
  '      await downloadStorageObject(accounts.A.office, legacyPath, legacyBucket),',
  '      "Office should retain metadata-less legacy private storage reads",',
  '    );',
  '    await expectDenied(',
  '      await downloadStorageObject(accounts.A.electrician, legacyPath, legacyBucket),',
  '      "Electrician must not read metadata-less legacy private storage",',
  '    );',
);

for (const [label, snippet] of [
  ["own job-document metadata", ownMetadata],
  ["other-customer job-document metadata", otherCustomerMetadata],
  ["legacy field upload expectation", legacyUpload],
]) {
  assert.equal(integrationSource.split(snippet).length - 1, 1, `Expected one ${label} anchor`);
}

const patchedIntegration = integrationSource
  .replace(ownMetadata, safeOwnMetadata)
  .replace(otherCustomerMetadata, safeOtherCustomerMetadata + roleCoverage)
  .replace(legacyUpload, safeLegacyUpload);

for (const phrase of [
  "Electrician should download a field job document",
  "Electrician should read assigned job-document metadata",
  "Co-assigned electrician should read assigned job-document metadata",
  "Electrician must not read metadata for a soft-deleted job document",
  "Electrician must not download a soft-deleted job document",
  "Office should retain metadata for a soft-deleted job document",
  "Office should retain soft-deleted job-document download access",
  "Electrician should regain assigned metadata only after document restoration",
  "Electrician should regain the assigned download only after document restoration",
  "Electrician must not read unassigned job-document metadata",
  "Electrician must not download an unassigned job document",
  "Office should retain unassigned job-document download access",
  "Assigned electrician must not download another organisation's job document",
  "Customer must not download an unshared job document",
  "Electrician must not upload a field survey photo without an assigned upload intent",
  "Electrician must not register field survey photo metadata without an assigned upload intent",
  "Electrician should download a field survey photo",
  "Electrician should read assigned survey photo metadata",
  "Electrician must not read unassigned survey photo metadata",
  "Electrician must not download an unassigned survey photo",
  "Customer must not download an internal survey photo",
  "Electrician must not read expense receipt metadata",
  "Customer must not read expense receipt metadata",
  "Electrician must not download a private expense receipt",
  "Customer must not download a private expense receipt",
  "Electrician must not overwrite a private expense receipt",
  "Electrician must not read unknown private metadata",
  "Customer must not read unknown private metadata",
  "Electrician must not upload to metadata-less legacy storage",
  "Electrician must not read metadata-less legacy private storage",
]) {
  assert.match(patchedIntegration, new RegExp(phrase.replaceAll(" ", "\\s+"), "i"));
}

test("live RLS runner proves private Storage follows source-collection roles", () => {
  const temporaryDirectory = mkdtempSync(join(tmpdir(), "jr-os-private-role-rls-"));
  const temporaryRunner = join(temporaryDirectory, "run-supabase-rls.integration.mjs");
  const temporaryIntegration = join(temporaryDirectory, "supabase-rls.integration.mjs");
  try {
    writeFileSync(temporaryRunner, runnerSource, "utf8");
    writeFileSync(temporaryIntegration, patchedIntegration, "utf8");
    const result = spawnSync(process.execPath, [temporaryRunner], {
      cwd: process.cwd(),
      env: process.env,
      stdio: "inherit",
    });
    if (result.error) throw result.error;
    assert.equal(result.status ?? 1, 0, "Private-file role live RLS wrapper should complete successfully");
  } finally {
    rmSync(temporaryDirectory, { recursive: true, force: true });
  }
});
