import type { JobPack, Material } from "./models";

const createdAt = new Date(0).toISOString();

function material(
  id: string,
  name: string,
  category: Material["category"],
  unit: Material["unit"],
  tradeCost: number,
  sellPrice: number,
  manufacturer = "Generic",
  supplier = "",
  favourite = false,
): Material {
  return {
    id,
    name,
    category,
    manufacturer,
    supplier,
    supplierUrl: "",
    stockCode: "",
    unit,
    tradeCost,
    sellPrice,
    favourite,
    notes: "Starter-library guide price. Replace with your current trade price and preferred brand before quoting.",
    priceSource: "Imported",
    priceHistory: [],
    createdAt,
    updatedAt: createdAt,
  };
}

export const starterMaterials: Material[] = [
  material("starter-mat-001", "1.0mm² twin and earth cable", "Cable", "Metre", 0.62, 0.9, "Generic", "", true),
  material("starter-mat-002", "1.5mm² twin and earth cable", "Cable", "Metre", 0.82, 1.15, "Generic", "", true),
  material("starter-mat-003", "2.5mm² twin and earth cable", "Cable", "Metre", 1.18, 1.65, "Generic", "", true),
  material("starter-mat-004", "4.0mm² twin and earth cable", "Cable", "Metre", 2.05, 2.85),
  material("starter-mat-005", "6.0mm² twin and earth cable", "Cable", "Metre", 2.85, 3.95),
  material("starter-mat-006", "10.0mm² twin and earth cable", "Cable", "Metre", 5.1, 7.1),
  material("starter-mat-007", "3 core and earth 1.0mm²", "Cable", "Metre", 1.02, 1.45),
  material("starter-mat-008", "3 core and earth 1.5mm²", "Cable", "Metre", 1.38, 1.95),
  material("starter-mat-009", "1.5mm² 3 core heat-resistant flex", "Cable", "Metre", 1.45, 2.05),
  material("starter-mat-010", "2.5mm² 3 core heat-resistant flex", "Cable", "Metre", 2.2, 3.1),
  material("starter-mat-011", "2.5mm² 3 core SWA", "Cable", "Metre", 2.3, 3.25),
  material("starter-mat-012", "4.0mm² 3 core SWA", "Cable", "Metre", 3.1, 4.35),
  material("starter-mat-013", "6.0mm² 3 core SWA", "Cable", "Metre", 4.35, 6.1),
  material("starter-mat-014", "10.0mm² 3 core SWA", "Cable", "Metre", 6.9, 9.65),
  material("starter-mat-015", "10mm² green/yellow bonding conductor", "Cable", "Metre", 1.45, 2.05),
  material("starter-mat-016", "16mm² green/yellow earthing conductor", "Cable", "Metre", 2.25, 3.15),
  material("starter-mat-017", "20mm heavy gauge PVC conduit", "Containment", "Metre", 1.25, 1.85, "Generic", "", true),
  material("starter-mat-018", "25mm heavy gauge PVC conduit", "Containment", "Metre", 1.75, 2.45),
  material("starter-mat-019", "20mm conduit accessories allowance", "Containment", "Pack", 4.5, 6.5),
  material("starter-mat-020", "25mm conduit accessories allowance", "Containment", "Pack", 5.5, 7.75),
  material("starter-mat-021", "25x16mm mini trunking", "Containment", "Metre", 1.35, 1.95),
  material("starter-mat-022", "38x25mm mini trunking", "Containment", "Metre", 2.25, 3.2),
  material("starter-mat-023", "Single metal back box 25mm", "Accessories", "Each", 0.75, 1.15, "Generic", "", true),
  material("starter-mat-024", "Double metal back box 25mm", "Accessories", "Each", 1.05, 1.55, "Generic", "", true),
  material("starter-mat-025", "Single metal back box 35mm", "Accessories", "Each", 0.95, 1.4),
  material("starter-mat-026", "Double metal back box 35mm", "Accessories", "Each", 1.25, 1.85),
  material("starter-mat-027", "1 gang dry-lining box", "Accessories", "Each", 0.85, 1.3),
  material("starter-mat-028", "2 gang dry-lining box", "Accessories", "Each", 1.15, 1.7),
  material("starter-mat-029", "13A double switched socket", "Accessories", "Each", 3.8, 6.5, "Generic", "", true),
  material("starter-mat-030", "13A single switched socket", "Accessories", "Each", 2.8, 4.75),
  material("starter-mat-031", "13A switched fused connection unit", "Accessories", "Each", 4.1, 6.95, "Generic", "", true),
  material("starter-mat-032", "13A unswitched fused connection unit", "Accessories", "Each", 3.9, 6.6),
  material("starter-mat-033", "20A double-pole switch", "Accessories", "Each", 5.2, 8.5),
  material("starter-mat-034", "45A cooker control unit", "Accessories", "Each", 8.5, 13.5),
  material("starter-mat-035", "45A cooker outlet plate", "Accessories", "Each", 4.6, 7.5),
  material("starter-mat-036", "1 gang 1 way light switch", "Accessories", "Each", 1.6, 2.8),
  material("starter-mat-037", "1 gang 2 way light switch", "Accessories", "Each", 1.8, 3.1),
  material("starter-mat-038", "2 gang 2 way light switch", "Accessories", "Each", 2.6, 4.4),
  material("starter-mat-039", "Ceiling rose", "Accessories", "Each", 1.5, 2.6),
  material("starter-mat-040", "Maintenance-free junction box allowance", "Accessories", "Each", 5.5, 8.5, "Wago", "", true),
  material("starter-mat-041", "Wago connectors and enclosure allowance", "Accessories", "Pack", 8.5, 12.5, "Wago"),
  material("starter-mat-042", "IP66 outdoor double socket", "Accessories", "Each", 18, 28, "Generic", "", true),
  material("starter-mat-043", "IP65 adaptable box", "Accessories", "Each", 5.5, 8.5),
  material("starter-mat-044", "SWA gland pack 20S", "Accessories", "Pack", 4.8, 7.25),
  material("starter-mat-045", "SWA gland pack 25", "Accessories", "Pack", 6.2, 9.25),
  material("starter-mat-046", "6A Type B RCBO", "Protection", "Each", 18, 28, "Generic", "", true),
  material("starter-mat-047", "16A Type B RCBO", "Protection", "Each", 18, 28),
  material("starter-mat-048", "20A Type B RCBO", "Protection", "Each", 18, 28),
  material("starter-mat-049", "32A Type B RCBO", "Protection", "Each", 18, 28, "Generic", "", true),
  material("starter-mat-050", "40A Type B RCBO", "Protection", "Each", 19, 29.5),
  material("starter-mat-051", "50A Type B RCBO", "Protection", "Each", 21, 32),
  material("starter-mat-052", "Main switch consumer unit 10 way with SPD", "Protection", "Each", 115, 165, "Generic", "", true),
  material("starter-mat-053", "Main switch consumer unit 14 way with SPD", "Protection", "Each", 145, 205),
  material("starter-mat-054", "Consumer unit labels, tails and sundries allowance", "Protection", "Pack", 35, 52),
  material("starter-mat-055", "100A double-pole isolator", "Protection", "Each", 18, 28),
  material("starter-mat-056", "LED batten 4ft", "Lighting", "Each", 22, 34, "Generic", "", true),
  material("starter-mat-057", "LED batten 5ft", "Lighting", "Each", 28, 42),
  material("starter-mat-058", "Fire-rated LED downlight", "Lighting", "Each", 9.5, 15, "Generic", "", true),
  material("starter-mat-059", "LED bulkhead", "Lighting", "Each", 18, 28),
  material("starter-mat-060", "PIR LED floodlight", "Lighting", "Each", 28, 45),
  material("starter-mat-061", "Bathroom inline fan kit", "Other", "Each", 65, 95),
  material("starter-mat-062", "3 pole fan isolator", "Accessories", "Each", 4.5, 7.25),
  material("starter-mat-063", "Mains interlinked smoke alarm", "Fire alarm", "Each", 24, 36, "Generic", "", true),
  material("starter-mat-064", "Mains interlinked heat alarm", "Fire alarm", "Each", 26, 39),
  material("starter-mat-065", "Emergency LED bulkhead", "Emergency lighting", "Each", 24, 38, "Generic", "", true),
  material("starter-mat-066", "Emergency exit sign", "Emergency lighting", "Each", 32, 48),
  material("starter-mat-067", "EV charger cable and protection allowance", "EV", "Pack", 165, 235),
  material("starter-mat-068", "Earth rod kit", "Protection", "Pack", 24, 38),
  material("starter-mat-069", "Testing and certification allowance", "Testing", "Each", 0, 35, "JR Electrical Services", "", true),
  material("starter-mat-070", "General fixings and sundries allowance", "Other", "Pack", 8, 15, "Generic", "", true),
];

function pack(
  id: string,
  name: string,
  category: string,
  description: string,
  labourHours: number,
  materialLines: Array<[string, string, number, number]>,
  testingRequirements: string,
  certificatesRequired: string,
  notes: string,
): JobPack {
  return {
    id,
    name,
    category,
    description,
    labourDescription: "Electrician labour, installation, termination and tidy-up",
    labourHours,
    labourRate: 50,
    materials: materialLines.map(([materialId, lineDescription, quantity, unitPrice], index) => ({
      id: `${id}-line-${index + 1}`,
      materialId,
      description: lineDescription,
      quantity,
      unitPrice,
    })),
    testingRequirements,
    certificatesRequired,
    notes,
    createdAt,
    updatedAt: createdAt,
  };
}

export const starterJobPacks: JobPack[] = [
  pack("starter-pack-001", "Add one double socket", "Commercial small works", "Add one new double socket from a suitable existing circuit, subject to testing and access.", 3, [["starter-mat-003", "2.5mm² twin and earth cable", 10, 1.65], ["starter-mat-024", "Double metal back box", 1, 1.55], ["starter-mat-029", "Double switched socket", 1, 6.5], ["starter-mat-070", "Fixings and sundries", 1, 15]], "Test altered circuit and record results.", "Minor Works Certificate where applicable.", "Making good and decoration excluded unless added."),
  pack("starter-pack-002", "Move one double socket", "Commercial small works", "Relocate one existing double socket locally using the existing circuit where suitable.", 3.5, [["starter-mat-003", "2.5mm² twin and earth cable", 8, 1.65], ["starter-mat-024", "Double metal back box", 1, 1.55], ["starter-mat-029", "Double switched socket", 1, 6.5], ["starter-mat-040", "Maintenance-free joint allowance", 1, 8.5], ["starter-mat-070", "Fixings and sundries", 1, 15]], "Test altered circuit and confirm continuity, insulation resistance and polarity.", "Minor Works Certificate where applicable.", "Route, access and making good to be confirmed on site."),
  pack("starter-pack-003", "Replace ten socket or switch faceplates", "Commercial small works", "Replace ten standard white accessories on existing serviceable wiring and boxes.", 4, [["starter-mat-029", "Accessory allowance", 10, 6.5], ["starter-mat-070", "Sundries", 1, 15]], "Functional checks, polarity and earth continuity as applicable.", "Minor Works Certificate not normally required for like-for-like replacement; record test results where appropriate.", "Decorative, USB, metal or specialist accessories require repricing."),
  pack("starter-pack-004", "Install outdoor double socket", "Commercial small works", "Install one IP-rated outdoor socket from a suitable RCD/RCBO-protected circuit.", 4.5, [["starter-mat-003", "2.5mm² cable", 12, 1.65], ["starter-mat-042", "IP66 outdoor double socket", 1, 28], ["starter-mat-021", "Mini trunking or containment allowance", 4, 1.95], ["starter-mat-070", "Fixings and sundries", 1, 15]], "Test circuit, RCD/RCBO operation, polarity and Zs.", "Minor Works Certificate.", "Assumes a suitable nearby circuit and straightforward surface route."),
  pack("starter-pack-005", "Bathroom inline fan installation", "Commercial small works", "Install an inline bathroom fan, isolator and local duct/electrical connections.", 6, [["starter-mat-061", "Inline fan kit", 1, 95], ["starter-mat-062", "3 pole fan isolator", 1, 7.25], ["starter-mat-008", "3 core and earth cable", 12, 1.95], ["starter-mat-021", "Containment allowance", 3, 1.95], ["starter-mat-070", "Fixings and sundries", 1, 15]], "Test supply, switching, timer/humidistat operation and protective measures.", "Minor Works Certificate.", "Core drilling, extensive ducting and making good excluded unless stated."),
  pack("starter-pack-006", "Replace consumer unit - 10 way", "Consumer unit", "Replace an existing consumer unit with a metal main-switch RCBO board including SPD, subject to survey and testing.", 12, [["starter-mat-052", "10 way consumer unit with SPD", 1, 165], ["starter-mat-046", "6A RCBO", 2, 28], ["starter-mat-049", "32A RCBO", 3, 28], ["starter-mat-048", "20A RCBO", 2, 28], ["starter-mat-050", "40A RCBO", 1, 29.5], ["starter-mat-054", "Labels, tails and sundries allowance", 1, 52]], "Full pre-change checks and post-installation verification of all connected circuits.", "Electrical Installation Certificate and Building Regulations notification where required.", "Faults, remedial works, bonding upgrades and DNO/metering work excluded unless identified and priced."),
  pack("starter-pack-007", "Domestic EICR - up to 8 circuits", "EICR", "Electrical Installation Condition Report for a typical domestic installation with up to eight circuits.", 4.5, [["starter-mat-069", "Testing and certification administration", 1, 35]], "Inspection and testing in accordance with the agreed extent and limitations.", "Electrical Installation Condition Report.", "Remedial work is excluded and quoted separately."),
  pack("starter-pack-008", "Domestic EICR - 9 to 16 circuits", "EICR", "Electrical Installation Condition Report for a larger domestic installation with nine to sixteen circuits.", 7, [["starter-mat-069", "Testing and certification administration", 1, 35]], "Inspection and testing in accordance with the agreed extent and limitations.", "Electrical Installation Condition Report.", "Remedial work is excluded and quoted separately."),
  pack("starter-pack-009", "Fault finding - first two hours", "Fault finding", "Initial attendance and structured electrical fault finding for up to two hours.", 2, [["starter-mat-070", "Minor test leads, connectors and sundries allowance", 1, 15]], "Safe isolation, visual inspection and appropriate diagnostic testing.", "Minor Works Certificate only if repair work is completed and certification is applicable.", "Additional time and replacement materials are charged separately after customer approval."),
  pack("starter-pack-010", "Install cooker circuit", "Commercial small works", "Install a new cooker radial circuit, control switch and outlet from a suitable distribution board.", 8, [["starter-mat-005", "6.0mm² twin and earth cable", 20, 3.95], ["starter-mat-050", "40A RCBO", 1, 29.5], ["starter-mat-034", "Cooker control unit", 1, 13.5], ["starter-mat-035", "Cooker outlet plate", 1, 7.5], ["starter-mat-025", "35mm single back box", 2, 1.4], ["starter-mat-070", "Fixings and sundries", 1, 15]], "Full verification of new circuit including RCD/RCBO tests.", "Electrical Installation Certificate or Minor Works Certificate depending on scope.", "Route assumes reasonable access; chasing and making good excluded."),
  pack("starter-pack-011", "Install four LED downlights", "Lighting", "Install four fire-rated LED downlights using a suitable existing lighting circuit.", 5, [["starter-mat-058", "Fire-rated LED downlight", 4, 15], ["starter-mat-002", "1.5mm² twin and earth cable", 15, 1.15], ["starter-mat-041", "Connectors and enclosure allowance", 1, 12.5], ["starter-mat-070", "Fixings and sundries", 1, 15]], "Test lighting circuit, polarity, continuity and insulation resistance as applicable.", "Minor Works Certificate where applicable.", "Assumes accessible ceiling void and no asbestos or structural restrictions."),
  pack("starter-pack-012", "Replace one LED batten", "Lighting", "Remove one existing fitting and install one standard LED batten on a serviceable supply.", 2, [["starter-mat-056", "4ft LED batten", 1, 34], ["starter-mat-070", "Fixings and sundries", 1, 15]], "Functional test and electrical safety checks.", "Minor Works Certificate where applicable.", "Access equipment and emergency variants may alter the price."),
  pack("starter-pack-013", "Replace one emergency bulkhead", "Emergency lighting", "Replace one existing emergency bulkhead and commission its operation.", 2.5, [["starter-mat-065", "Emergency LED bulkhead", 1, 38], ["starter-mat-070", "Fixings and sundries", 1, 15]], "Functional test, charge indicator check and simulated supply failure.", "Emergency lighting test record or certificate as required.", "Full duration test may require a return visit."),
  pack("starter-pack-014", "Install two interlinked smoke alarms", "Fire alarm", "Install two mains-powered interlinked smoke alarms from a suitable supply.", 5, [["starter-mat-063", "Mains interlinked smoke alarm", 2, 36], ["starter-mat-008", "3 core and earth cable", 15, 1.95], ["starter-mat-070", "Fixings and sundries", 1, 15]], "Test supply, interlink and alarm operation.", "Minor Works Certificate and alarm test record where applicable.", "Access, decoration and additional detection grades to be confirmed."),
  pack("starter-pack-015", "Garage supply - 6mm² SWA up to 20m", "Commercial small works", "Install a small garage supply using up to 20 metres of 6mm² SWA, local distribution and basic final circuits.", 16, [["starter-mat-013", "6.0mm² 3 core SWA", 20, 6.1], ["starter-mat-044", "SWA gland packs", 2, 7.25], ["starter-mat-052", "Garage distribution/protection allowance", 1, 165], ["starter-mat-042", "Outdoor double socket", 1, 28], ["starter-mat-056", "LED batten", 1, 34], ["starter-mat-070", "Fixings and sundries", 2, 15]], "Verify supply characteristics, cable design, earthing arrangement and all new circuits.", "Electrical Installation Certificate and notification where required.", "Groundworks, trenching, structural work and DNO issues excluded."),
  pack("starter-pack-016", "EV charger electrical provision", "EV charger", "Electrical provision for a standard domestic EV charger subject to survey, load assessment and manufacturer requirements.", 12, [["starter-mat-067", "EV cable and protection allowance", 1, 235], ["starter-mat-070", "Fixings and sundries", 2, 15]], "Load assessment, earthing review, RCD/protection verification and full commissioning tests.", "Electrical Installation Certificate and Building Regulations notification where required.", "Charger unit, DNO application, load management and groundworks may be separate depending on specification."),
  pack("starter-pack-017", "Small kitchen electrical alteration", "Commercial small works", "Typical small kitchen alteration covering socket moves/additions, appliance points and accessory changes.", 16, [["starter-mat-003", "2.5mm² twin and earth cable", 35, 1.65], ["starter-mat-029", "Double sockets", 4, 6.5], ["starter-mat-031", "Switched fused connection units", 3, 6.95], ["starter-mat-024", "Double back boxes", 4, 1.55], ["starter-mat-023", "Single back boxes", 3, 1.15], ["starter-mat-040", "Maintenance-free joint allowance", 2, 8.5], ["starter-mat-070", "Fixings and sundries", 2, 15]], "Test all altered circuits and confirm protective measures.", "Minor Works Certificate or Electrical Installation Certificate depending on scope.", "Appliances, faceplate upgrades, chasing and making good to be confirmed."),
  pack("starter-pack-018", "One-bedroom property rewire starter", "Rewire", "Starter template for a one-bedroom domestic rewire. Adjust points, routes, accessories and board requirements after survey.", 80, [["starter-mat-003", "2.5mm² twin and earth cable", 250, 1.65], ["starter-mat-002", "1.5mm² twin and earth cable", 200, 1.15], ["starter-mat-007", "3 core and earth cable", 50, 1.45], ["starter-mat-052", "Consumer unit and protection allowance", 1, 165], ["starter-mat-029", "Double sockets", 18, 6.5], ["starter-mat-036", "Light switches", 8, 2.8], ["starter-mat-039", "Ceiling roses", 8, 2.6], ["starter-mat-063", "Smoke alarms", 2, 36], ["starter-mat-070", "Fixings and sundries allowance", 8, 15]], "Full initial verification of the new installation.", "Electrical Installation Certificate and Building Regulations notification.", "Survey-based template only. Building work, decoration, asbestos, specialist finishes and temporary supplies excluded unless stated."),
  pack("starter-pack-019", "Three-bedroom property rewire starter", "Rewire", "Starter template for a typical three-bedroom domestic rewire. Fully adjust after survey and drawings.", 160, [["starter-mat-003", "2.5mm² twin and earth cable", 500, 1.65], ["starter-mat-002", "1.5mm² twin and earth cable", 400, 1.15], ["starter-mat-007", "3 core and earth cable", 100, 1.45], ["starter-mat-005", "6.0mm² twin and earth cable", 35, 3.95], ["starter-mat-053", "Consumer unit and protection allowance", 1, 205], ["starter-mat-029", "Double sockets", 36, 6.5], ["starter-mat-036", "Light switches", 14, 2.8], ["starter-mat-039", "Ceiling roses", 14, 2.6], ["starter-mat-063", "Smoke alarms", 3, 36], ["starter-mat-064", "Heat alarm", 1, 39], ["starter-mat-070", "Fixings and sundries allowance", 14, 15]], "Full initial verification of the new installation.", "Electrical Installation Certificate and Building Regulations notification.", "Survey-based template only. Labour, points and material quantities must be checked against the final design."),
  pack("starter-pack-020", "Commercial office power alteration", "Commercial small works", "Starter pack for minor office socket additions and alterations on an existing suitable circuit.", 8, [["starter-mat-003", "2.5mm² twin and earth cable", 25, 1.65], ["starter-mat-029", "Double sockets", 4, 6.5], ["starter-mat-024", "Double back boxes", 4, 1.55], ["starter-mat-021", "Mini trunking", 12, 1.95], ["starter-mat-070", "Fixings and sundries", 2, 15]], "Test altered circuit and record results, including RCD/RCBO operation where applicable.", "Minor Works Certificate.", "Out-of-hours working, permits, access equipment and fire stopping are additional unless stated."),
];
